[package]
name = "steam-protobuf"
version = "0.1.0"
authors = ["Martin <martin@hotmail.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
glob = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
protobuf = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "master"}
protoc-rust = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "master" }

