[package]
name = "steam-language-gen"
version = "0.1.0"
authors = ["Martin <martin@hotmail.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
regex = "1.3.1"
petgraph = "0.4.13"

#derives
num-traits = "0.2"
num-derive = "0.3"
bitflags = "1.2.1"
derive-new = "0.5.8"

# serde
serde = {version = "1.0.101", features = ["derive"]}
serde_json = "1.0.41"
serde_repr = "0.1.5"
bincode = "1.2.0"

steam-language-gen-derive = { path = "../steam-language-gen-derive" }

[dependencies.Inflector]
version = "*"
default-features = false
