[package]
name = "steam-totp"
version = "0.1.0"
authors = ["Martin <martin@hotmail.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
openssl = "0.10.25"
bytes = "0.4.12"
sha-1 = "0.8.1"
hmac = "0.7.1"
crypto-mac = { version = "0.7.0", features = ["std"] }
